# Generated by Django 4.2.30 on 2026-05-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_household_head_alter_household_household_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Building",
        ),
        migrations.DeleteModel(
            name="Facility",
        ),
        migrations.DeleteModel(
            name="Institution",
        ),
        migrations.DeleteModel(
            name="LandBody",
        ),
        migrations.DeleteModel(
            name="MedicalStaff",
        ),
        migrations.DeleteModel(
            name="Professional",
        ),
        migrations.DeleteModel(
            name="RoadNetwork",
        ),
        migrations.DeleteModel(
            name="Utility",
        ),
        migrations.DeleteModel(
            name="WaterBody",
        ),
    ]
